[project]
name = "text-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "google-genai>=1.73.1",
    "pydantic>=2.13.3",
    "pydantic-ai-slim[google]>=1.103.0",
    "pydantic-settings>=2.14.0",
    "pypdf[full]>=6.10.2",
    "python-docx>=1.2.0",
    "requests>=2.33.1",
    "streamlit>=1.57.0",
    "stripe>=15.1.0",
]
